export function buildJoradpUrl(year: number, jorfNumber: number, lang: 'ar' | 'fr'): string {
  const padded = String(jorfNumber).padStart(3, '0');
  const prefix = lang === 'ar' ? 'A' : 'F';
  const folder = lang === 'ar' ? 'jo-arabe' : 'jo-francais';
  return `https://www.joradp.dz/FTP/${folder}/${year}/${prefix}${year}${padded}.pdf`;
}

export const LAWS_DATA = [
  {
    titleAr: "الدستور الجزائري",
    titleFr: "Constitution algérienne",
    referenceNumber: "96-438",
    lawType: "مرسوم رئاسي",
    category: "دستور",
    jorfYear: 1996,
    jorfNumber: 76,
  },
  {
    titleAr: "التعديل الدستوري 2020",
    titleFr: "Constitution amendment 2020",
    referenceNumber: "20-01",
    lawType: "قانون",
    category: "دستور",
    jorfYear: 2020,
    jorfNumber: 82,
  },
  {
    titleAr: "قانون الإجراءات المدنية والإدارية",
    titleFr: "Code de procédures civiles et administratives",
    referenceNumber: "08-09",
    lawType: "قانون",
    category: "إجراءات قضائية إدارية",
    jorfYear: 2008,
    jorfNumber: 21,
  },
  {
    titleAr: "القانون الأساسي العام للوظيفة العمومية",
    titleFr: "Statut général de la fonction publique",
    referenceNumber: "06-03",
    lawType: "أمر",
    category: "وظيف عمومي",
    jorfYear: 2006,
    jorfNumber: 46,
  },
  {
    titleAr: "المرسوم التنفيذي المتعلق بممارسة حق الإضراب في الوظيف العمومي",
    titleFr: "Décret exécutif relatif au droit de grève",
    referenceNumber: "90-02",
    lawType: "مرسوم تنفيذي",
    category: "وظيف عمومي",
    jorfYear: 1990,
    jorfNumber: 2,
  },
  {
    titleAr: "قانون البلدية",
    titleFr: "Loi relative à la commune",
    referenceNumber: "11-10",
    lawType: "قانون",
    category: "إدارة محلية",
    jorfYear: 2011,
    jorfNumber: 37,
  },
  {
    titleAr: "قانون الولاية",
    titleFr: "Loi relative à la wilaya",
    referenceNumber: "12-07",
    lawType: "قانون",
    category: "إدارة محلية",
    jorfYear: 2012,
    jorfNumber: 12,
  },
  {
    titleAr: "قانون الصفقات العمومية وتفويضات المرفق العام",
    titleFr: "Marchés publics et délégations de service public",
    referenceNumber: "15-247",
    lawType: "مرسوم رئاسي",
    category: "صفقات عمومية",
    jorfYear: 2015,
    jorfNumber: 50,
  },
  {
    titleAr: "تعديل قانون الصفقات العمومية 2023",
    titleFr: "Modification des marchés publics 2023",
    referenceNumber: "23-316",
    lawType: "مرسوم رئاسي",
    category: "صفقات عمومية",
    jorfYear: 2023,
    jorfNumber: 68,
  },
  {
    titleAr: "قانون تنظيم السجن وإعادة الإدماج الاجتماعي للمحبوسين",
    titleFr: "Loi relative à l'organisation pénitentiaire",
    referenceNumber: "05-04",
    lawType: "قانون",
    category: "تنظيم إداري",
    jorfYear: 2005,
    jorfNumber: 12,
  },
  {
    titleAr: "المرسوم التنفيذي المتعلق بتنظيم الإدارة المركزية",
    titleFr: "Décret exécutif relatif à l'organisation de l'administration centrale",
    referenceNumber: "20-140",
    lawType: "مرسوم تنفيذي",
    category: "تنظيم إداري",
    jorfYear: 2020,
    jorfNumber: 24,
  },
  {
    titleAr: "قانون المالية العامة",
    titleFr: "Loi relative aux lois de finances",
    referenceNumber: "84-17",
    lawType: "قانون",
    category: "مالية عامة",
    jorfYear: 1984,
    jorfNumber: 28,
  },
  {
    titleAr: "القانون المدني",
    titleFr: "Code civil",
    referenceNumber: "75-58",
    lawType: "أمر",
    category: "قوانين مرجعية",
    jorfYear: 1975,
    jorfNumber: 78,
  },
  {
    titleAr: "قانون العقوبات",
    titleFr: "Code pénal",
    referenceNumber: "66-156",
    lawType: "أمر",
    category: "قوانين مرجعية",
    jorfYear: 1966,
    jorfNumber: 49,
  },
  {
    titleAr: "قانون الأسرة",
    titleFr: "Code de la famille",
    referenceNumber: "84-11",
    lawType: "قانون",
    category: "قوانين مرجعية",
    jorfYear: 1984,
    jorfNumber: 24,
  },
  {
    titleAr: "قانون العمل",
    titleFr: "Code du travail",
    referenceNumber: "90-11",
    lawType: "قانون",
    category: "قوانين مرجعية",
    jorfYear: 1990,
    jorfNumber: 17,
  },
];