import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const laws = [
  {
    id: 'law_001',
    titleAr: 'المدنية الجزائرية',
    titleFr: 'Code Civil Algerien',
    titleEn: 'Algerian Civil Code',
    category: 'مدني',
    referenceNumber: 'CC-DZ-1975',
    year: 1975,
    publicationDate: '1975-06-18',
    journalOfficiel: 'الجريدة الرسمية عدد 57',
    descriptionAr: 'مدونة القانون المدني الجزائري',
    descriptionFr: 'Code de la loi civile algérienne',
    descriptionEn: 'Algerian Civil Code law',
    contentAr: 'أحكام القانون المدني الجزائري',
    contentFr: 'Dispositions du code civil algérien',
    isPremium: false,
    isVerified: true,
    source: 'الجمهورية الجزائرية',
    jorfYear: 1975,
    jorfNumber: 57,
  },
  {
    id: 'law_002',
    titleAr: 'قانون العقوبات',
    titleFr: 'Code Pénal',
    titleEn: 'Penal Code',
    category: 'جنائي',
    referenceNumber: 'CP-DZ-1966',
    year: 1966,
    publicationDate: '1966-06-21',
    journalOfficiel: 'الجريدة الرسمية عدد 46',
    descriptionAr: 'قانون العقوبات الجزائري',
    descriptionFr: 'Code pénal algérien',
    descriptionEn: 'Algerian Penal Code',
    contentAr: 'أحكام قانون العقوبات',
    contentFr: 'Dispositions du code pénal',
    isPremium: false,
    isVerified: true,
    source: 'الجمهورية الجزائرية',
    jorfYear: 1966,
    jorfNumber: 46,
  },
  {
    id: 'law_003',
    titleAr: 'قانون الإجراءات المدنية',
    titleFr: 'Code de Procédure Civile',
    titleEn: 'Code of Civil Procedure',
    category: 'مدني',
    referenceNumber: 'CPC-DZ-1998',
    year: 1998,
    publicationDate: '1998-10-25',
    journalOfficiel: 'الجريدة الرسمية عدد 73',
    descriptionAr: 'قانون الإجراءات المدنية والإدارية',
    descriptionFr: 'Code de procédure civile et administrative',
    descriptionEn: 'Code of Civil and Administrative Procedure',
    contentAr: 'أحكام إجراءات التقاضي',
    contentFr: 'Dispositions de procédure',
    isPremium: false,
    isVerified: true,
    source: 'الجمهورية الجزائرية',
    jorfYear: 1998,
    jorfNumber: 73,
  },
  {
    id: 'law_004',
    titleAr: 'قانون التجارة',
    titleFr: 'Code de Commerce',
    titleEn: 'Commercial Code',
    category: 'تجاري',
    referenceNumber: 'CM-DZ-1989',
    year: 1989,
    publicationDate: '1989-07-20',
    journalOfficiel: 'الجريدة الرسمية عدد 44',
    descriptionAr: 'قانون التجارة الجزائري',
    descriptionFr: 'Code de commerce algérien',
    descriptionEn: 'Algerian Commercial Code',
    contentAr: 'أحكام قانون التجارة',
    contentFr: 'Dispositions du code de commerce',
    isPremium: false,
    isVerified: true,
    source: 'الجمهورية الجزائرية',
    jorfYear: 1989,
    jorfNumber: 44,
  },
  {
    id: 'law_005',
    titleAr: 'قانون العمل',
    titleFr: 'Code du Travail',
    titleEn: 'Labor Code',
    category: 'شغل',
    referenceNumber: 'CT-DZ-1990',
    year: 1990,
    publicationDate: '1990-04-14',
    journalOfficiel: 'الجريدة الرسمية عدد 24',
    descriptionAr: 'قانون التشريع الخاصة بالعمل',
    descriptionFr: 'Code du travail algérien',
    descriptionEn: 'Algerian Labor Code',
    contentAr: 'أحكام قانون العمل',
    contentFr: 'Dispositions du code du travail',
    isPremium: false,
    isVerified: true,
    source: 'الجمهورية الجزائرية',
    jorfYear: 1990,
    jorfNumber: 24,
  },
  {
    id: 'law_006',
    titleAr: 'قانون الأسرة',
    titleFr: 'Code de la Famille',
    titleEn: 'Family Code',
    category: 'أسري',
    referenceNumber: 'CF-DZ-1984',
    year: 1984,
    publicationDate: '1984-05-09',
    journalOfficiel: 'الجريدة الرسمية عدد 24',
    descriptionAr: 'قانون الأسرة والم遗产',
    descriptionFr: 'Code de la famille et des successions',
    descriptionEn: 'Family and Inheritance Code',
    contentAr: 'أحكام قانون الأسرة',
    contentFr: 'Dispositions du code de la famille',
    isPremium: false,
    isVerified: true,
    source: 'الجمهورية الجزائرية',
    jorfYear: 1984,
    jorfNumber: 24,
  },
  {
    id: 'law_007',
    titleAr: 'قانون الإجراءات الجنائية',
    titleFr: 'Code de Procédure Pénale',
    titleEn: 'Code of Criminal Procedure',
    category: 'جنائي',
    referenceNumber: 'CPP-DZ-1966',
    year: 1966,
    publicationDate: '1966-06-25',
    journalOfficiel: 'الجريدة الرسمية عدد 50',
    descriptionAr: 'قانون الإجراءات في المواد الجنائية',
    descriptionFr: 'Code de procédure pénale',
    descriptionEn: 'Code of Criminal Procedure',
    contentAr: 'أحكام الإجراءات الجنائية',
    contentFr: 'Dispositions de procédure pénale',
    isPremium: false,
    isVerified: true,
    source: 'الجمهورية الجزائرية',
    jorfYear: 1966,
    jorfNumber: 50,
  },
  {
    id: 'law_008',
    titleAr: 'قانون الضرائب',
    titleFr: 'Code des Impôts',
    titleEn: 'Tax Code',
    category: 'ضريبي',
    referenceNumber: 'CI-DZ-1985',
    year: 1985,
    publicationDate: '1985-12-31',
    journalOfficiel: 'الجريدة الرسمية عدد 54',
    descriptionAr: 'قانون الضرائب والزكاة',
    descriptionFr: 'Code des impôts et des taxes',
    descriptionEn: 'Tax Code',
    contentAr: 'أحكام قانون الضرائب',
    contentFr: 'Dispositions du code des impôts',
    isPremium: false,
    isVerified: true,
    source: 'الجمهورية الجزائرية',
    jorfYear: 1985,
    jorfNumber: 54,
  },
  {
    id: 'law_009',
    titleAr: 'قانون الجمارك',
    titleFr: 'Code des Douanes',
    titleEn: 'Customs Code',
    category: 'جمارك',
    referenceNumber: 'CD-DZ-1979',
    year: 1979,
    publicationDate: '1979-12-15',
    journalOfficiel: 'الجريدة الرسمية عدد 52',
    descriptionAr: 'قانون الجمارك والرسوم',
    descriptionFr: 'Code des douanes et droits indirects',
    descriptionEn: 'Algerian Customs Code',
    contentAr: 'أحكام قانون الجمارك',
    contentFr: 'Dispositions du code des douanes',
    isPremium: false,
    isVerified: true,
    source: 'الجمهورية الجزائرية',
    jorfYear: 1979,
    jorfNumber: 52,
  },
  {
    id: 'law_010',
    titleAr: 'قانون العقار',
    titleFr: 'Code de la Propriété',
    titleEn: 'Property Code',
    category: 'عقاري',
    referenceNumber: 'CP-DZ-1974',
    year: 1974,
    publicationDate: '1974-07-21',
    journalOfficiel: 'الجريدة الرسمية عدد 56',
    descriptionAr: 'قانون التصرف في العقارات',
    descriptionFr: 'Code de la propriété et des droits réels',
    descriptionEn: 'Property and Real Rights Code',
    contentAr: 'أحكام قانون العقار',
    contentFr: 'Dispositions du code de la propriété',
    isPremium: false,
    isVerified: true,
    source: 'الجمهورية الجزائرية',
    jorfYear: 1974,
    jorfNumber: 56,
  },
];

async function main() {
  for (const law of laws) {
    const created = await prisma.law.upsert({
      where: { id: law.id },
      update: {},
      create: law,
    });
    console.log('Created:', created.titleFr);
  }
  console.log('All 10 laws added!');
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());